### ISSUE TITLE
Need help running playbook

### ISSUE THREAD

**Issue by andrewm659** [sbaerlocher/ansible.snmp#20]
Do you have an example of how to run this playbook against a Windows server or Windows 10 machine?

**Comment by Tyneven** [comment]
In your playbook:
```yaml
---
- name: Install and configure SNMP
  hosts: windows_server
  roles:
     - snmp
```

Don't forget modify variables in your inventory if it necessary

Main.yml file in tasks, check distribution and version and apply some files according to distribution automatically.

WinRM must be configured on windows server or Windows 10 Machine.
Master Branch use DSC on Windows Server but DSC is available only for Powershell Version 5.
