### ISSUE TITLE
The error was: ansible.errors.AnsibleUndefinedVariable: 'snmp_agentadress_protocol' is undefined

### ISSUE THREAD

**Issue by dimaliv** [sbaerlocher/ansible.snmp#29]
Playbook:
```yaml
- hosts: host
  gather_facts: yes
  tasks:
    - name: snmp
      import_role: 
        name: sbaerlocher.snmp
      tags: [ configuration, packages ]
      vars:
        snmp_user: "{{ group_vars_snmp_secrets.snmp_user }}"
        snmp_password: "{{ group_vars_snmp_secrets.snmp_password }}"
        snmp_encryption: "{{ group_vars_snmp_secrets.snmp_encryption }}"`
```
Result:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'snmp_agentadress_protocol' is undefined
fatal: [host]: FAILED! => {
    "changed": false
}

MSG:

AnsibleUndefinedVariable: 'snmp_agentadress_protocol' is undefined
```
